### Numpy 배열 생성하기

Numpy is an abbreviation of "Numeric Python"
It's a library required for extensive areas like statistics, scientific calculation, computing, data analysis and more. 

Numpy array is quite similar to a list but it is faster and more efficient in memory use, therefore well-performing.

**1) np.array() , np.random.rand()**

In [1]:
import numpy as np

In [8]:
abc = np.array([1,2,3,4,3,3,2])
abc

array([1, 2, 3, 4, 3, 3, 2])

In [12]:
a=np.random.randint(6)

In [13]:
a

1

### 리스트와 numpy배열을 각각 생성, 두개를 비교해보자.

#### numpy 배열을 만드는 방법
1) array() 

2) 랜덤함수

##### List 생성

In [33]:
myList = [4,5,6,7]
myList

[4, 5, 6, 7]

##### numpy Array 생성

In [34]:
myArray = np.array(myList)
myArray

array([4, 5, 6, 7])

In [35]:
print(myList)
print(myArray)

[4, 5, 6, 7]
[4 5 6 7]


In [36]:
mylst = [[1,2,3],[45,5,3]]
nparray = np.array(mylst)
nparray #automatically recognize them as 'n-dimentional array', therefore, ndarray.

array([[ 1,  2,  3],
       [45,  5,  3]])

In [28]:
notMatrix=[[1,2,3],[2,3]]
tryNpArray=np.array(notMatrix)

<ipython-input-28-4705621ea4b1>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tryNpArray=np.array(notMatrix)


##### Slicing & Indexing

In [37]:
list_sub = myList[1:3] #숫자형 슬라이싱  #파이썬에서 변수는 snake_case
print(list_sub)

[5, 6]


In [38]:
arr_sub= myArray[1:3]  #numpy array도 슬라이싱이 된다!
print(arr_sub)

[5 6]


In [41]:
list_sub[0] = -5
arr_sub[0] = -5

print(list_sub)
print(arr_sub)
print(myList)
print(myArray)

[-5, 6]
[-5  6]
[4, 5, 6, 7]
[ 4 -5  6  7]


In [42]:
'''
List는 원본이 바뀌지 않는다 
WHEREAS
npArray는 원본 뷰가 바뀐다. 
::
메모리 활용 성능면에서는 np배열이 성능이 좋아진다.
'''

print(myList)
print(myArray) #Surprisingly, it takes on a fixed memory area. 

[4, 5, 6, 7]
[ 4 -5  6  7]


##### for loop with np.array

In [43]:
for i in myArray:
    print(i*3)

12
-15
18
21


##### Numpy 배열생성
- random submodule 사용

###### rand()

In [44]:
  #모르는 게 있을땐 '?'

np.random.rand(2,3) # 2-dimensional matrix


array([[0.0341553 , 0.89489803, 0.7650099 ],
       [0.82473287, 0.78122885, 0.32577344]])

In [46]:
np.random.rand(5) # 1-dimensional matrix

array([0.18747601, 0.42900802, 0.12194936, 0.3748436 , 0.07456895])

###### randint()

In [47]:
b = np.random.randint(1,10,5) # 1부터 10까지 숫자중 5개만 10 not included.
b

array([6, 6, 5, 3, 6])

###### randn 
- 가우시안 표준분포 값 (정규분포값)

In [49]:
c = np.random.randn(10,5)
c

array([[ 0.4081987 , -1.79332631,  0.50828097, -0.59892615, -0.02425781],
       [-1.14189784,  0.36723039,  0.52516543, -0.81107555, -1.39789916],
       [-1.32738352, -0.81144544,  1.12977337, -0.61830076,  0.53438241],
       [ 0.23704481,  0.1514986 ,  0.25756093,  0.20547064, -0.78387668],
       [-0.30695943,  1.69904184,  0.56067272,  0.65881554,  0.08886572],
       [ 0.63329776,  0.54037797, -1.63416128,  0.1729114 , -0.09673411],
       [ 1.07966612,  0.02075176, -0.59569926, -0.34894238,  0.92440641],
       [-0.71558039, -0.41545046, -0.11379355,  0.93165473, -0.74901945],
       [ 0.21188944,  0.75767454, -1.87304545, -0.44082505, -0.52316314],
       [ 1.27239334,  0.01127277,  1.33138033,  0.14415988, -0.59177002]])

##### numpy 배열 생성과 동시에 초기화 

In [50]:
zero = np.zeros(10).reshape(2,5)
one = np.ones(100).reshape(10,10)

print(zero)
print(one)
print(type(one[0][0]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<class 'numpy.float64'>


In [53]:
a1 = np.ones(10)
a5 = np.ones(10)*5  #곱하여 초기화값 설정.
a11 = np.ones(10)*11 

print(a1)
print(a5)
print(a11)

a3 = np.ones(10)+3 # 더하여 초기화값 설정.


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]


###### eye

In [67]:
ae = np.eye(3) #단위행렬 생성 -> matrix구조
ae

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
ae * ae  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###### arange

In [69]:
np.arange(0,3) # = np.arrange(3)
a = np.arange(3,18).reshape(3,5)
b = np.arange(3,18).reshape(5,3)


###### full()

In [70]:
afull = np.full((5,5),-11)  
#except for the elements being int32, it's practically the same as 
#np.zeros(25).reshape(5,5) -11

print(afull)

b = np.zeros(25).reshape(5,5) -11

print(b)


[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]
[[-11. -11. -11. -11. -11.]
 [-11. -11. -11. -11. -11.]
 [-11. -11. -11. -11. -11.]
 [-11. -11. -11. -11. -11.]
 [-11. -11. -11. -11. -11.]]
